const data = [
  {
    _id: 4,
    name: "Royal Spice",
    location: "Delhi",
    address: "MG Road, Delhi",
    type: "Veg",
    table_capacity: 8,
    availability: {
      "12:00 PM": true,
      "1:00 PM": true,
      "2:00 PM": false,
      "7:00 PM": false,
      "8:00 PM": true,
      "9:00 PM": true,
    },
  },
  {
    _id: 5,
    name: "The Bombay Biryani",
    location: "Mumbai",
    address: "Colaba Causeway, Mumbai",
    type: "Non Veg",
    table_capacity: 12,
    availability: {
      "12:00 PM": false,
      "1:00 PM": true,
      "2:00 PM": true,
      "7:00 PM": true,
      "8:00 PM": false,
      "9:00 PM": true,
    },
  },
  {
    _id: 6,
    name: "Chennai Delights",
    location: "Chennai",
    address: "T Nagar, Chennai",
    type: "Pure Veg",
    table_capacity: 10,
    availability: {
      "12:00 PM": true,
      "1:00 PM": false,
      "2:00 PM": true,
      "7:00 PM": true,
      "8:00 PM": true,
      "9:00 PM": false,
    },
  },
  {
    _id: 7,
    name: "Kolkata Kuisine",
    location: "Kolkata",
    address: "Park Street, Kolkata",
    type: "Non Veg",
    table_capacity: 9,
    availability: {
      "12:00 PM": false,
      "1:00 PM": false,
      "2:00 PM": true,
      "7:00 PM": true,
      "8:00 PM": false,
      "9:00 PM": true,
    },
  },
  {
    _id: 8,
    name: "Spicy Treat",
    location: "Hyderabad",
    address: "Banjara Hills, Hyderabad",
    type: "Veg",
    table_capacity: 5,
    availability: {
      "12:00 PM": true,
      "1:00 PM": true,
      "2:00 PM": true,
      "7:00 PM": false,
      "8:00 PM": false,
      "9:00 PM": false,
    },
  },
  {
    _id: 9,
    name: "Goa Grill",
    location: "Goa",
    address: "Calangute Beach, Goa",
    type: "Non Veg",
    table_capacity: 4,
    availability: {
      "12:00 PM": false,
      "1:00 PM": true,
      "2:00 PM": false,
      "7:00 PM": true,
      "8:00 PM": true,
      "9:00 PM": true,
    },
  },
  {
    _id: 10,
    name: "Punjabi Dhaba",
    location: "Ludhiana",
    address: "Main Bypass, Ludhiana",
    type: "Pure Veg",
    table_capacity: 6,
    availability: {
      "12:00 PM": true,
      "1:00 PM": false,
      "2:00 PM": false,
      "7:00 PM": true,
      "8:00 PM": false,
      "9:00 PM": true,
    },
  },
  {
    _id: 11,
    name: "Rajasthan Rasoi",
    location: "Jaipur",
    address: "Pink Square Mall, Jaipur",
    type: "Veg",
    table_capacity: 7,
    availability: {
      "12:00 PM": true,
      "1:00 PM": true,
      "2:00 PM": false,
      "7:00 PM": false,
      "8:00 PM": true,
      "9:00 PM": true,
    },
  },
  {
    _id: 12,
    name: "Kerala Flavours",
    location: "Kochi",
    address: "MG Road, Kochi",
    type: "Non Veg",
    table_capacity: 8,
    availability: {
      "12:00 PM": false,
      "1:00 PM": true,
      "2:00 PM": true,
      "7:00 PM": true,
      "8:00 PM": false,
      "9:00 PM": false,
    },
  },
  {
    _id: 13,
    name: "Gujarat Thali",
    location: "Ahmedabad",
    address: "Maninagar, Ahmedabad",
    type: "Pure Veg",
    table_capacity: 10,
    availability: {
      "12:00 PM": true,
      "1:00 PM": true,
      "2:00 PM": true,
      "7:00 PM": false,
      "8:00 PM": true,
      "9:00 PM": false,
    },
  },
  {
    _id: 14,
    name: "Mumbai Masala",
    location: "Mumbai",
    address: "Andheri West, Mumbai",
    type: "Non Veg",
    table_capacity: 14,
    availability: {
      "12:00 PM": true,
      "1:00 PM": false,
      "2:00 PM": false,
      "7:00 PM": true,
      "8:00 PM": true,
      "9:00 PM": true,
    },
  },
  {
    _id: 15,
    name: "Delhi Diner",
    location: "Delhi",
    address: "Connaught Place, Delhi",
    type: "Veg",
    table_capacity: 11,
    availability: {
      "12:00 PM": false,
      "1:00 PM": true,
      "2:00 PM": true,
      "7:00 PM": false,
      "8:00 PM": false,
      "9:00 PM": true,
    },
  },
  {
    _id: 16,
    name: "Namma Ooru",
    location: "Bangalore",
    address: "Indiranagar, Bangalore",
    type: "Veg",
    table_capacity: 6,
    availability: {
      "12:00 PM": true,
      "1:00 PM": true,
      "2:00 PM": false,
      "7:00 PM": false,
      "8:00 PM": true,
      "9:00 PM": false,
    },
  },
  {
    _id: 17,
    name: "Sea Breeze",
    location: "Vishakhapatnam",
    address: "RK Beach Road, Vizag",
    type: "Non Veg",
    table_capacity: 9,
    availability: {
      "12:00 PM": false,
      "1:00 PM": false,
      "2:00 PM": true,
      "7:00 PM": true,
      "8:00 PM": false,
      "9:00 PM": true,
    },
  },
  {
    _id: 18,
    name: "Biryani Blues",
    location: "Hyderabad",
    address: "Hi-Tech City, Hyderabad",
    type: "Non Veg",
    table_capacity: 15,
    availability: {
      "12:00 PM": true,
      "1:00 PM": true,
      "2:00 PM": false,
      "7:00 PM": false,
      "8:00 PM": true,
      "9:00 PM": true,
    },
  },
  {
    _id: 19,
    name: "Sikkim Sizzlers",
    location: "Gangtok",
    address: "MG Marg, Gangtok",
    type: "Veg",
    table_capacity: 5,
    availability: {
      "12:00 PM": false,
      "1:00 PM": true,
      "2:00 PM": true,
      "7:00 PM": true,
      "8:00 PM": false,
      "9:00 PM": false,
    },
  },
  {
    _id: 20,
    name: "Udupi Utsav",
    location: "Mangalore",
    address: "Car Street, Mangalore",
    type: "Pure Veg",
    table_capacity: 10,
    availability: {
      "12:00 PM": true,
      "1:00 PM": false,
      "2:00 PM": true,
      "7:00 PM": false,
      "8:00 PM": true,
      "9:00 PM": false,
    },
  },
  {
    _id: 21,
    name: "Madurai Meals",
    location: "Madurai",
    address: "KK Nagar, Madurai",
    type: "Veg",
    table_capacity: 6,
    availability: {
      "12:00 PM": false,
      "1:00 PM": true,
      "2:00 PM": true,
      "7:00 PM": true,
      "8:00 PM": false,
      "9:00 PM": true,
    },
  },
  {
    _id: 22,
    name: "Taste of Nagpur",
    location: "Nagpur",
    address: "Sadar, Nagpur",
    type: "Non Veg",
    table_capacity: 8,
    availability: {
      "12:00 PM": false,
      "1:00 PM": false,
      "2:00 PM": false,
      "7:00 PM": true,
      "8:00 PM": true,
      "9:00 PM": true,
    },
  },
  {
    _id: 23,
    name: "Bangalore Bites",
    location: "Bangalore",
    address: "Jayanagar, Bangalore",
    type: "Veg",
    table_capacity: 9,
    availability: {
      "12:00 PM": true,
      "1:00 PM": true,
      "2:00 PM": false,
      "7:00 PM": true,
      "8:00 PM": true,
      "9:00 PM": false,
    },
  },
  {
    _id: 34,
    name: "Ranchi Rasoi",
    location: "Ranchi",
    address: "Main Road, Ranchi",
    type: "Veg",
    table_capacity: 6,
    availability: {
      "12:00 PM": true,
      "1:00 PM": false,
      "2:00 PM": true,
      "7:00 PM": false,
      "8:00 PM": true,
      "9:00 PM": true,
    },
  },
  {
    _id: 35,
    name: "The Coastal Bite",
    location: "Mangalore",
    address: "Panambur Road, Mangalore",
    type: "Non Veg",
    table_capacity: 9,
    availability: {
      "12:00 PM": true,
      "1:00 PM": true,
      "2:00 PM": false,
      "7:00 PM": true,
      "8:00 PM": false,
      "9:00 PM": true,
    },
  },
  {
    _id: 36,
    name: "Deccan Diner",
    location: "Pune",
    address: "Baner Road, Pune",
    type: "Veg",
    table_capacity: 7,
    availability: {
      "12:00 PM": false,
      "1:00 PM": true,
      "2:00 PM": true,
      "7:00 PM": true,
      "8:00 PM": false,
      "9:00 PM": false,
    },
  },
  {
    _id: 37,
    name: "Assam Aromas",
    location: "Guwahati",
    address: "GS Road, Guwahati",
    type: "Non Veg",
    table_capacity: 5,
    availability: {
      "12:00 PM": true,
      "1:00 PM": false,
      "2:00 PM": false,
      "7:00 PM": true,
      "8:00 PM": true,
      "9:00 PM": true,
    },
  },
  {
    _id: 38,
    name: "The Rajmahal",
    location: "Udaipur",
    address: "Lake Pichola, Udaipur",
    type: "Pure Veg",
    table_capacity: 12,
    availability: {
      "12:00 PM": false,
      "1:00 PM": false,
      "2:00 PM": true,
      "7:00 PM": true,
      "8:00 PM": true,
      "9:00 PM": false,
    },
  },
  {
    _id: 39,
    name: "Fusion Feast",
    location: "Bengaluru",
    address: "Church Street, Bengaluru",
    type: "Non Veg",
    table_capacity: 10,
    availability: {
      "12:00 PM": true,
      "1:00 PM": true,
      "2:00 PM": true,
      "7:00 PM": false,
      "8:00 PM": false,
      "9:00 PM": true,
    },
  },
  {
    _id: 40,
    name: "Jharkhand Junction",
    location: "Jamshedpur",
    address: "Bistupur, Jamshedpur",
    type: "Veg",
    table_capacity: 6,
    availability: {
      "12:00 PM": false,
      "1:00 PM": true,
      "2:00 PM": false,
      "7:00 PM": true,
      "8:00 PM": true,
      "9:00 PM": false,
    },
  },
  {
    _id: 41,
    name: "Thanjavur Tiffins",
    location: "Thanjavur",
    address: "Old Bus Stand, Thanjavur",
    type: "Pure Veg",
    table_capacity: 4,
    availability: {
      "12:00 PM": true,
      "1:00 PM": false,
      "2:00 PM": true,
      "7:00 PM": true,
      "8:00 PM": false,
      "9:00 PM": false,
    },
  },
  {
    _id: 42,
    name: "Konkan Kitchen",
    location: "Ratnagiri",
    address: "Ganpatipule Road, Ratnagiri",
    type: "Non Veg",
    table_capacity: 8,
    availability: {
      "12:00 PM": true,
      "1:00 PM": true,
      "2:00 PM": true,
      "7:00 PM": false,
      "8:00 PM": true,
      "9:00 PM": false,
    },
  },
  {
    _id: 43,
    name: "Himalayan Herbs",
    location: "Shimla",
    address: "Mall Road, Shimla",
    type: "Veg",
    table_capacity: 7,
    availability: {
      "12:00 PM": false,
      "1:00 PM": false,
      "2:00 PM": true,
      "7:00 PM": true,
      "8:00 PM": true,
      "9:00 PM": true,
    },
  },
  {
    _id: 44,
    name: "Silicon Curry",
    location: "Bengaluru",
    address: "Electronic City, Bengaluru",
    type: "Non Veg",
    table_capacity: 11,
    availability: {
      "12:00 PM": true,
      "1:00 PM": true,
      "2:00 PM": false,
      "7:00 PM": true,
      "8:00 PM": false,
      "9:00 PM": false,
    },
  },
  {
    _id: 45,
    name: "Lucknowi Flavours",
    location: "Lucknow",
    address: "Hazratganj, Lucknow",
    type: "Non Veg",
    table_capacity: 10,
    availability: {
      "12:00 PM": false,
      "1:00 PM": true,
      "2:00 PM": true,
      "7:00 PM": false,
      "8:00 PM": true,
      "9:00 PM": true,
    },
  },
  {
    _id: 46,
    name: "Kanpur Curry House",
    location: "Kanpur",
    address: "Mall Road, Kanpur",
    type: "Veg",
    table_capacity: 6,
    availability: {
      "12:00 PM": false,
      "1:00 PM": true,
      "2:00 PM": false,
      "7:00 PM": true,
      "8:00 PM": false,
      "9:00 PM": true,
    },
  },
  {
    _id: 47,
    name: "Agra Sweets & Savories",
    location: "Agra",
    address: "Taj Ganj, Agra",
    type: "Pure Veg",
    table_capacity: 5,
    availability: {
      "12:00 PM": true,
      "1:00 PM": false,
      "2:00 PM": true,
      "7:00 PM": true,
      "8:00 PM": false,
      "9:00 PM": true,
    },
  },
  {
    _id: 48,
    name: "Sundarbans Spices",
    location: "Kolkata",
    address: "Salt Lake, Kolkata",
    type: "Non Veg",
    table_capacity: 9,
    availability: {
      "12:00 PM": false,
      "1:00 PM": true,
      "2:00 PM": false,
      "7:00 PM": true,
      "8:00 PM": true,
      "9:00 PM": false,
    },
  },
  {
    _id: 49,
    name: "Chandni Chowk Chaat",
    location: "Delhi",
    address: "Chandni Chowk, Delhi",
    type: "Pure Veg",
    table_capacity: 6,
    availability: {
      "12:00 PM": true,
      "1:00 PM": true,
      "2:00 PM": false,
      "7:00 PM": false,
      "8:00 PM": true,
      "9:00 PM": false,
    },
  },
  {
    _id: 50,
    name: "Desi Junction",
    location: "Noida",
    address: "Sector 18, Noida",
    type: "Veg",
    table_capacity: 8,
    availability: {
      "12:00 PM": false,
      "1:00 PM": false,
      "2:00 PM": true,
      "7:00 PM": true,
      "8:00 PM": true,
      "9:00 PM": false,
    },
  },
  {
    _id: 51,
    name: "Vellore Veggie Villa",
    location: "Vellore",
    address: "Katpadi Road, Vellore",
    type: "Pure Veg",
    table_capacity: 7,
    availability: {
      "12:00 PM": true,
      "1:00 PM": false,
      "2:00 PM": true,
      "7:00 PM": false,
      "8:00 PM": false,
      "9:00 PM": true,
    },
  },
  {
    _id: 52,
    name: "Dilli 6",
    location: "Delhi",
    address: "Karol Bagh, Delhi",
    type: "Non Veg",
    table_capacity: 10,
    availability: {
      "12:00 PM": true,
      "1:00 PM": false,
      "2:00 PM": false,
      "7:00 PM": true,
      "8:00 PM": true,
      "9:00 PM": true,
    },
  },
  {
    _id: 53,
    name: "Rajkot Rasoda",
    location: "Rajkot",
    address: "Kalavad Road, Rajkot",
    type: "Veg",
    table_capacity: 5,
    availability: {
      "12:00 PM": false,
      "1:00 PM": true,
      "2:00 PM": true,
      "7:00 PM": true,
      "8:00 PM": false,
      "9:00 PM": true,
    },
  },
];

data.hotelname = data.name;
delete data.name;
console.log(data);
